version: '3.8'
x-django-environment: &django-environment
  - ENV_FILE
  # Ensure username and pw match with POSTGRES_* defined below
  - DATABASE_URL=postgis://watch:changemeforprod@db/watch
  - CACHE_URL=rediscache://redis:6379
  - STATIC_ROOT=/srv/static
  - LC_CTYPE=C.UTF-8
  - DEBUG
  - DEPLOYMENT_TYPE
  - ALLOWED_HOSTS
  - COOKIE_PREFIX
  - INTERNAL_IPS
  - SENTRY_DSN
  - SECRET_KEY
  - CONFIGURE_LOGGING
  - OIDC_ISSUER_URL
  - OIDC_CLIENT_ID
  - OIDC_CLIENT_SECRET
  - AZURE_AD_CLIENT_ID
  - AZURE_AD_CLIENT_SECRET
  - GOOGLE_CLIENT_ID
  - GOOGLE_CLIENT_SECRET
  - MAILGUN_API_KEY
  - MAILGUN_SENDER_DOMAIN
  - MAILGUN_REGION
  - MAILJET_API_KEY
  - MAILJET_SECRET_KEY
  - HOSTNAME_PLAN_DOMAINS
  - ELASTICSEARCH_URL
  - ADMIN_WILDCARD_DOMAIN
  - CELERY_BROKER_URL=redis://redis:6379
  - CELERY_RESULT_BACKEND=redis://redis:6379
  - GOOGLE_MAPS_V3_APIKEY
  - ALLOWED_SENDER_EMAILS
  - SERVER_EMAIL
  - DEFAULT_FROM_EMAIL

x-django-build: &django-build
  context: .
  dockerfile: docker/app/Dockerfile
  args:
    - EXTRA_PYPI_INDEX
    - STATIC_ROOT

x-common-runtime: &common-runtime
  restart: 'no'

services:
  db:
    # Set DB_IMAGE to specify the image name and tag for docker-compose push
    image: ${DB_IMAGE-kausal-watch-postgres}
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    <<: *common-runtime
    environment:
      # Ensure these match with DATABASE_URL defined above
      - POSTGRES_USER=watch
      - POSTGRES_PASSWORD=changemeforprod
    volumes:
      - db_data:/var/lib/postgresql/data/

  redis:
    image: ${REDIS_IMAGE-redis:6.0-alpine}
    <<: *common-runtime

  app:
    # Set APP_IMAGE to specify the image name and tag for docker-compose push
    image: ${APP_IMAGE-kausal-watch}
    build: *django-build
    <<: *common-runtime
    volumes:
      - aplans_media:/srv/media
    environment: *django-environment
    depends_on:
      - db
      - redis
    command: uwsgi

  celery-worker:
    build: *django-build
    <<: *common-runtime
    environment: *django-environment
    depends_on:
      - db
      - redis
    command: celery worker

  celery-beat:
    build: *django-build
    <<: *common-runtime
    environment: *django-environment
    depends_on:
      - db
      - redis
    command: celery beat

  celery-exporter:
    image: ovalmoney/celery-exporter
    <<: *common-runtime
    depends_on:
      - redis
    ports:
      - "${CELERY_EXPORTER_PORT:-127.0.0.1:9540}:9540"
    command: --enable-events

  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE-kausal-watch-elasticsearch}
    build:
      context: ./docker/elasticsearch
      dockerfile: ./Dockerfile
    <<: *common-runtime
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_PASSWORD
    deploy:
      resources:
        limits:
          memory: ${ELASTIC_MEM_LIMIT:-2G}

volumes:
  db_data:
  aplans_media:
  elasticsearch_data:
