version: '3.2'
services:
  db:
    container_name: aplans-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=aplans
    volumes:
      - db_data:/var/lib/postgresql/data/

  app:
    container_name: aplans
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    restart: always
    volumes:
      - aplans_media:/srv/media
    environment:
      - DATABASE_URL=postgres://aplans@db/aplans
      - STATIC_ROOT=/srv/static
      - LC_CTYPE=C.UTF-8
      - DEBUG
      - ALLOWED_HOSTS
      - COOKIE_PREFIX
      - INTERNAL_IPS
      - SENTRY_DSN
      - SECRET_KEY
      - OIDC_ISSUER_URL
      - OIDC_CLIENT_ID
      - OIDC_CLIENT_SECRET
      - MAILGUN_API_KEY
      - MAILGUN_SENDER_DOMAIN
      - MAILGUN_REGION
    ports:
      - "${HOST_PORT:-8000}:8000"
    depends_on:
      - db

volumes:
  db_data:
  aplans_media:
